name: Build and Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy React App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # specify the Node.js version you are using

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: build docker image
        uses: actions/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{secrets.DOCKER_HUB_USER_NAME}}/react-Flow:latest
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME}}
          password: ${{ secrets.DOCKER_HUB_TOKEN}}
      - name: push to docker hub
        uses: actions/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USER_NAME}}/react-Flow:latest